"""The episode compiler — one seeded run of the whole show, as playback JSON.

`arena/web/divorce/` is a cinematic PLAYER, not a simulator: every number it
renders comes from this trace, and every trace event was generated by the
same engine code the kill harness registered (SPEC.md §7: nothing on screen
is scripted — this module just records the real run). The live per-user
route (/v1/divorce/run) is a thin wrapper over run_episode.

Usage:
    python3 -m divorce.trace --preset bloodbath
    python3 -m divorce.trace --preset spreadsheets
    python3 -m divorce.trace --preset nodecree
    python3 -m divorce.trace --all      # emit all three into arena/web/divorce/
"""
from __future__ import annotations

import argparse
import json
import os

import numpy as np

from divorce import arms, elicit, personas, receipt

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "arena", "web", "divorce")

PRESETS = {
    # The demo opener: both hills on the dog — the head-on collision jackpot.
    "bloodbath": {
        "wildcard_label": "his mother's painting",
        "fronts": ["dog", "vinyl"],
        "a": {"name": "Dana", "archetype": "scorched_earth", "hill": "dog",
              "sliders": {"pettiness": 0.7, "spite": 0.45, "patience": 0.7}},
        "b": {"name": "Morgan", "archetype": "sentimental_hoarder", "hill": "dog",
              "sliders": {"pettiness": 0.85, "spite": 0.15, "patience": 0.6}},
    },
    # The post-credits stinger: two rational people divorce in seconds.
    "spreadsheets": {
        "wildcard_label": "the IKEA futon",
        "fronts": [],
        "a": {"name": "Alex", "archetype": "spreadsheet", "hill": "espresso",
              "sliders": {"pettiness": 0.05, "spite": 0.0, "patience": 0.5}},
        "b": {"name": "Sam", "archetype": "spreadsheet", "hill": "espresso",
              "sliders": {"pettiness": 0.05, "spite": 0.0, "patience": 0.5}},
    },
    # The honest failure: wants a NO DECREE (seed is searched, see main()).
    "nodecree": {
        "wildcard_label": "the karaoke machine",
        "fronts": ["dog", "wildcard"],
        "a": {"name": "Riley", "archetype": "sentimental_hoarder", "hill": "dog",
              "sliders": {"pettiness": 0.95, "spite": 0.3, "patience": 1.0}},
        "b": {"name": "Jordan", "archetype": "ledger", "hill": "dog",
              "sliders": {"pettiness": 0.95, "spite": 0.35, "patience": 1.0}},
    },
}


def _compile_pair(seed: int, spec: dict):
    rng = np.random.default_rng([seed, 0])
    mults = {f: float(rng.uniform(*personas.FRONT_MULT_RANGE))
             for f in spec["fronts"]}
    market = personas.sample_market(rng)   # one retail table per case
    pa = personas.compile_persona(rng, "A", spec["a"]["archetype"],
                                  spec["a"]["hill"], mults,
                                  sliders=spec["a"]["sliders"], market=market)
    pb = personas.compile_persona(rng, "B", spec["b"]["archetype"],
                                  spec["b"]["hill"], mults,
                                  sliders=spec["b"]["sliders"], market=market)
    return pa, pb, rng


def run_episode(seed: int, spec: dict, prior=None) -> dict:
    """The full four-act run, deterministic from (seed, spec)."""
    prior = prior if prior is not None else elicit.build_asset_prior()
    outcomes = arms.enumerate_outcomes()
    pa, pb, rng = _compile_pair(seed, spec)
    seal_a, seal_b = receipt.seal_persona(pa), receipt.seal_persona(pb)

    # Act I — your lawyers' way (the montage feed is the real exchange log).
    res_i = arms.run_arm_i(pa, pb, rng)

    # Acts II + III — the interview and the drafts, via the real mediator.
    def flip_o(o):
        return {k: 1.0 - v for k, v in o.items()}

    stated_a = {"lam": pa.lam, "fight_cost": pa.fight_cost,
                "optimism": pa.optimism}
    stated_b = {"lam": pb.lam, "fight_cost": pb.fight_cost,
                "optimism": pb.optimism}
    med = elicit.mediate(
        prior,
        elicit.make_answerer(pa, uid=seed * 100_003),
        elicit.make_answerer(pb, uid=seed * 100_003 + 1),
        stated_a, stated_b, outcomes=outcomes,
        ratify_a=lambda o: pa.utility(o) >= pa.walk_away,
        ratify_b=lambda o: pb.utility(flip_o(o)) >= pb.walk_away)

    settled = med["proposal"] is not None
    dec = None
    scorecard = None
    if settled:
        shares_a = med["proposal"]
        fa, fb = pa.utility(shares_a), pb.utility(flip_o(shares_a))
        joint = (fa - pa.walk_away) + (fb - pb.walk_away)
        tax = arms.pettiness_tax(pa, pb, outcomes)
        rcpt = receipt.build_settlement_receipt(
            med, stated_a, stated_b, seal_a, seal_b,
            context={"seed": seed, "cal_seed": elicit.CAL_SEED,
                     "q_budget": elicit.Q_BUDGET,
                     "drafts_max": elicit.DRAFTS_MAX})
        dec = {"shares_a": {k: round(v, 4) for k, v in shares_a.items()},
               "receipt": rcpt}
        scorecard = {
            "joint_surplus": round(joint),
            "surplus_a": round(fa - pa.walk_away),
            "surplus_b": round(fb - pb.walk_away),
            "split_a_pct": round(100 * (fa - pa.walk_away) / joint) if joint > 0 else 50,
            "pettiness_tax_a": round(tax["a"]),
            "pettiness_tax_b": round(tax["b"]),
            "hill_autopsy": {
                "a": {"hill": pa.hill, "cost": round(tax["a"]),
                      "retail": round(pa.market_values[pa.hill])},
                "b": {"hill": pb.hill, "cost": round(tax["b"]),
                      "retail": round(pb.market_values[pb.hill])},
            },
            "arm_i_joint_surplus": round(res_i["joint_surplus"]),
        }
    else:
        res_o = arms.run_arm_o(pa, pb, outcomes)   # was there EVER a deal?
        dec = {"no_decree": True,
               "no_zopa": not res_o["settled"],     # true: math couldn't save it
               "mediator_abstained": res_o["settled"]}  # true: not confident

    def cast(p: personas.Persona, name: str, spec_side: dict) -> dict:
        return {"name": name, "archetype": p.archetype,
                "sliders": {"pettiness": round(p.pettiness, 2),
                            "spite": round(p.lam, 2),
                            "patience": round(p.patience, 2)},
                "hill": p.hill,                    # revealed at the flip
                "fight_cost": round(p.fight_cost),
                # Declared court confidence, as a percentage — the chrome's
                # "believes the judge will side with them: 62%" line. Both
                # sides' numbers can't both be right; that's the point.
                "court_confidence_pct": round(100 * (0.5 + p.optimism)),
                "seal": receipt.seal_persona(p)}

    return {
        "meta": {"preset_seed": seed, "wildcard_label": spec["wildcard_label"],
                 "engine": "divorce/* on gametheory+preflearn+notary; every "
                           "event below is a recorded engine output"},
        "cast": {"a": cast(pa, spec["a"]["name"], spec["a"]),
                 "b": cast(pb, spec["b"]["name"], spec["b"])},
        "act1": {"exchange_log": res_i["exchange_log"],
                 "per_item_exchanges": res_i["per_item_exchanges"],
                 "unsettled": res_i["unsettled"],
                 "settled_fraction": res_i["settled_fraction"]},
        "act2": {"trace_a": med["trace_a"], "trace_b": med["trace_b"],
                 "n_questions": med["n_questions"]},
        "act3": {"drafts": [{"proposal": {k: round(v, 4) for k, v in
                                          d["proposal"].items()},
                             "ok_a": d["ok_a"], "ok_b": d["ok_b"]}
                            for d in med.get("drafts", [])]},
        "decree": dec,
        "scorecard": scorecard,
        "flip": {"a": {"payload": receipt.seal_payload(pa), "seal": seal_a,
                       "walk_away": round(pa.walk_away)},
                 "b": {"payload": receipt.seal_payload(pb), "seal": seal_b,
                       "walk_away": round(pb.walk_away)}},
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--preset", choices=sorted(PRESETS))
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--out-dir", default=OUT_DIR)
    args = ap.parse_args()
    os.makedirs(args.out_dir, exist_ok=True)
    prior = elicit.build_asset_prior()

    def emit(name: str) -> None:
        spec = PRESETS[name]
        if args.seed is not None:
            seed, ep = args.seed, run_episode(args.seed, spec, prior)
        else:
            seed, ep = _find_seed(name, spec, prior)
        path = os.path.join(args.out_dir, f"trace-{name}.json")
        with open(path, "w") as f:
            json.dump(ep, f, indent=1)
        d = ep["decree"]
        story = ("NO DECREE" if d.get("no_decree") else
                 f"settled, drafts={len(ep['act3']['drafts'])}, "
                 f"taxA=${ep['scorecard']['pettiness_tax_a']:,}")
        print(f"[{name}] seed={seed}: {story}  -> {path}")

    for name in (sorted(PRESETS) if args.all else [args.preset]):
        emit(name)


def _find_seed(name: str, spec: dict, prior) -> tuple[int, dict]:
    """Deterministic seed search for each preset's REQUIRED story shape —
    the shape is searched, never faked: every emitted trace is a real run.
    bloodbath: dog deadlocks in Act I, decree signed, nonzero pettiness tax
    (prefer a refused draft for the 'Draft #2. Refused. Noted.' beat).
    spreadsheets: decree signed with zero tax. nodecree: no decree."""
    fallback = None
    for seed in range(1, 120):
        ep = run_episode(seed, spec, prior)
        d, sc = ep["decree"], ep["scorecard"]
        if name == "nodecree":
            if d.get("no_decree"):
                return seed, ep
        elif name == "spreadsheets":
            # Near-zero, not exactly zero: even a Spreadsheet's hill carries a
            # small spike, and the card must print the real number.
            if not d.get("no_decree") and \
                    sc["pettiness_tax_a"] + sc["pettiness_tax_b"] <= 500:
                return seed, ep
        else:  # bloodbath
            good = (not d.get("no_decree")
                    and "dog" in ep["act1"]["unsettled"]
                    and ep["act1"]["per_item_exchanges"].get("dog", 0) >= 8
                    and max(sc["pettiness_tax_a"], sc["pettiness_tax_b"]) > 1000)
            if good and fallback is None:
                fallback = (seed, ep)
            if good and len(ep["act3"]["drafts"]) >= 2:
                return seed, ep
    if fallback is not None:
        return fallback
    raise SystemExit(f"no seed in range produced the '{name}' story shape — "
                     f"that itself is a finding; widen the search or revisit")


if __name__ == "__main__":
    main()
