"""
Validation for the multi-issue logrolling tool (gametheory.negotiation.bundle).

The single-issue +12% does NOT transfer here — different engine, its own claim.

Honest design (addresses two fair critiques of the first version):
  * The headline must not be "+X% vs always-pick-the-middle", which is a strawman.
    The meaningful question is: what does INFERRING the counterparty's priorities
    actually BUY over the SAME engine run WITHOUT inference (uniform-prior Nash)?
    So the primary baseline is `negotiate_bundle(..., their_offers=None)` — the
    identical Pareto/Nash machinery with no opponent model. (Midpoint is kept only
    as a floor reference.)
  * The counterparty's offers must not be generated by the same model the filter
    assumes (that would be circular). We measure under TWO different opponent
    offer processes — a softmax over their utility AND a Boulware conceder — and
    report the range.

    python -m gametheory.negotiation.bundle_validation
"""
from __future__ import annotations

import itertools

import numpy as np

from gametheory.negotiation.bundle import negotiate_bundle, _norm01


def _random_profile(rng, n_issues=4, n_opts=4):
    names = [f"issue{i}" for i in range(n_issues)]
    issues = []
    for i in range(n_issues):
        myu = rng.random(n_opts)
        opposed = (myu.max() - myu) + rng.normal(0, 0.15, n_opts)  # mostly competitive
        issues.append({"name": names[i], "options": list(range(n_opts)),
                       "my_utility": list(myu), "their_utility": list(opposed)})
    my_w = rng.dirichlet(np.ones(n_issues))
    true_their_w = rng.dirichlet(np.ones(n_issues))
    return names, issues, dict(zip(names, my_w)), true_their_w


def _their_true_per_dim(issues):
    return [_norm01(iss["their_utility"]) for iss in issues]


def _offers_softmax(rng, names, issues, true_their_w, k=4):
    """They reveal preference via a softmax over their true utility (process A)."""
    their_u = _their_true_per_dim(issues)
    n_opts = len(issues[0]["options"])
    offers = []
    for _ in range(k):
        offer = {}
        for i, name in enumerate(names):
            logits = their_u[i] * (3.0 + 8.0 * true_their_w[i])
            p = np.exp(logits - logits.max()); p /= p.sum()
            offer[name] = int(rng.choice(n_opts, p=p))
        offers.append(offer)
    return offers


def _offers_boulware(names, issues, true_their_w, k=4):
    """They open at their best full package and concede down their ranked list
    (process B — deterministic, NOT the filter's assumed softmax form)."""
    their_u = _their_true_per_dim(issues)
    grid = list(itertools.product(*[range(len(i["options"])) for i in issues]))
    grid.sort(key=lambda c: sum(true_their_w[i] * their_u[i][c[i]] for i in range(len(names))),
              reverse=True)
    offers = []
    for j in range(k):
        idx = int((j / k) * (len(grid) // 2))   # concede from best toward the median
        offers.append({names[i]: grid[idx][i] for i in range(len(names))})
    return offers


def _joint_under_true(issues, names, rec, my_w_dict, true_their_w):
    my_u = [_norm01(iss["my_utility"]) for iss in issues]
    their_u = _their_true_per_dim(issues)
    my_w = np.array([my_w_dict[n] for n in names]); my_w /= my_w.sum()
    u_me = sum(my_w[i] * my_u[i][rec[names[i]]] for i in range(len(names)))
    u_them = sum(true_their_w[i] * their_u[i][rec[names[i]]] for i in range(len(names)))
    return float(u_me), float(u_them)


def _midpoint(issues, names):
    return {n: len(iss["options"]) // 2 for n, iss in zip(names, issues)}


def _run_one(rng, opponent):
    names, issues, my_w, true_w = _random_profile(rng)
    offers = (_offers_softmax(rng, names, issues, true_w) if opponent == "softmax"
              else _offers_boulware(names, issues, true_w))
    with_inf = negotiate_bundle(issues=issues, their_offers=offers, my_priorities=my_w)
    no_inf = negotiate_bundle(issues=issues, their_offers=None, my_priorities=my_w)
    if with_inf["recommended_offer"] is None or no_inf["recommended_offer"] is None:
        return None
    inferred = np.array([with_inf["inferred_their_priorities"][n] for n in names])
    r = (float(np.corrcoef(inferred, true_w)[0, 1])
         if np.std(inferred) > 1e-9 and np.std(true_w) > 1e-9 else np.nan)
    jw = sum(_joint_under_true(issues, names, with_inf["recommended_offer"], my_w, true_w))
    jn = sum(_joint_under_true(issues, names, no_inf["recommended_offer"], my_w, true_w))
    jm = sum(_joint_under_true(issues, names, _midpoint(issues, names), my_w, true_w))
    return {"r": r, "joint_with": jw, "joint_no_inf": jn, "joint_mid": jm}


def run(n_profiles=300, seed=7):
    print("=" * 74)
    print("  MULTI-ISSUE LOGROLLING — VALIDATION (honest baselines)")
    print("=" * 74)
    out = {}
    for opponent in ("softmax", "boulware"):
        rng = np.random.default_rng(seed)
        rows = [_run_one(rng, opponent) for _ in range(n_profiles)]
        rows = [r for r in rows if r]
        r_mean = float(np.nanmean([x["r"] for x in rows]))
        jw = np.mean([x["joint_with"] for x in rows])
        jn = np.mean([x["joint_no_inf"] for x in rows])
        jm = np.mean([x["joint_mid"] for x in rows])
        lift_vs_noinf = jw / jn - 1.0
        lift_vs_mid = jw / jm - 1.0
        beats_noinf = np.mean([x["joint_with"] >= x["joint_no_inf"] for x in rows])
        out[opponent] = dict(n=len(rows), r=r_mean, jw=jw, jn=jn, jm=jm,
                             lift_vs_noinf=lift_vs_noinf, lift_vs_mid=lift_vs_mid,
                             beats_noinf=beats_noinf)
        print(f"\n  opponent process = {opponent} ({len(rows)} profiles, 4 issues x 4 options)")
        print(f"    priority recovery (inferred vs true):      r = {r_mean:+.3f}")
        print(f"    joint surplus  with-inference:   {jw:.3f}")
        print(f"                   no-inference (uniform prior): {jn:.3f}   -> inference lift {lift_vs_noinf:+.1%}")
        print(f"                   naive-midpoint (floor ref):   {jm:.3f}   -> vs midpoint {lift_vs_mid:+.1%}")
        print(f"    beats no-inference baseline: {beats_noinf:.0%} of profiles")
    print("-" * 74)
    print("  HONEST READ: the meaningful number is 'inference lift' (with- vs no-")
    print("  inference, same engine). The vs-midpoint figure is a floor reference,")
    print("  not the headline. Recovery r is modest, so the inference lift is real")
    print("  but small — and it holds across two different opponent processes.")
    return out


# ─── PEER path validation: two SNHP agents negotiate a full contract ──────
# The honest question: does peer_mode (truthful BATNA + cooperative efficient
# selection) grow JOINT welfare vs two adversarial SNHP agents, on the SAME
# profiles? We run a real bilateral negotiation both ways, paired per seed.

def _bilateral_profile(rng, n_issues=4, n_opts=4):
    """A two-sided contract: per-issue seller-favourable directions, and each
    side's own TRUE priority weights (private)."""
    names = [f"issue{i}" for i in range(n_issues)]
    dirs = [np.clip(np.linspace(0, 1, n_opts) + rng.normal(0, 0.06, n_opts), 0, 1)
            for _ in range(n_issues)]
    wa = rng.dirichlet(np.ones(n_issues))
    wb = rng.dirichlet(np.ones(n_issues))
    return names, dirs, wa, wb


def _side_issues(names, dirs, role):
    """role 'a' favours high options (dir), 'b' favours low (1-dir)."""
    out = []
    for name, d in zip(names, dirs):
        my = list(d) if role == "a" else [1 - x for x in d]
        their = [1 - x for x in d] if role == "a" else list(d)
        out.append({"name": name, "options": list(range(len(d))),
                    "my_utility": my, "their_utility": their})
    return out


def _true_util(names, dirs, w, role, pkg):
    w = np.asarray(w) / np.sum(w)
    tot = 0.0
    for i, name in enumerate(names):
        opt = pkg[name]
        val = dirs[i][opt] if role == "a" else (1 - dirs[i][opt])
        tot += w[i] * val
    return float(tot)


def _run_bilateral(rng, peer, rounds=6, batna=0.30):
    names, dirs, wa, wb = _bilateral_profile(rng)
    a_iss, b_iss = _side_issues(names, dirs, "a"), _side_issues(names, dirs, "b")
    wa_d = dict(zip(names, wa)); wb_d = dict(zip(names, wb))
    # peers exchange truthful BATNAs; adversaries use the blind default
    a_est = batna if peer else 0.40
    b_est = batna if peer else 0.40
    a_off, b_off, settled = [], [], None
    for t in range(rounds):
        if t % 2 == 0:
            adv = negotiate_bundle(issues=a_iss, their_offers=b_off or None,
                                   my_priorities=wa_d, my_batna=batna,
                                   their_batna_estimate=a_est, peer_mode=peer)
            if adv["action"] == "accept" and b_off:
                settled = b_off[-1]; break
            if adv["recommended_offer"] is None:
                break
            a_off.append(adv["recommended_offer"])
        else:
            adv = negotiate_bundle(issues=b_iss, their_offers=a_off or None,
                                   my_priorities=wb_d, my_batna=batna,
                                   their_batna_estimate=b_est, peer_mode=peer)
            if adv["action"] == "accept" and a_off:
                settled = a_off[-1]; break
            if adv["recommended_offer"] is None:
                break
            b_off.append(adv["recommended_offer"])
    if settled is None:
        settled = (a_off or b_off or [None])[-1]
    if settled is None:
        return None
    ua = _true_util(names, dirs, wa, "a", settled)
    ub = _true_util(names, dirs, wb, "b", settled)
    return ua + ub, min(ua, ub)


def run_peer(n_profiles=400, seed=11):
    print("=" * 74)
    print("  MULTI-ISSUE PEER PATH — VALIDATION (paired, two SNHP agents)")
    print("=" * 74)
    peer_j, adv_j, peer_fair, adv_fair, wins = [], [], [], [], 0
    for i in range(n_profiles):
        rp = np.random.default_rng(seed + i)
        p = _run_bilateral(rp, peer=True)
        ra = np.random.default_rng(seed + i)
        a = _run_bilateral(ra, peer=False)
        if not p or not a:
            continue
        peer_j.append(p[0]); adv_j.append(a[0])
        peer_fair.append(p[1]); adv_fair.append(a[1])
        wins += (p[0] >= a[0])
    n = len(peer_j)
    pj, aj = np.mean(peer_j), np.mean(adv_j)
    lift = pj / aj - 1.0
    # paired sign test
    diffs = np.array(peer_j) - np.array(adv_j)
    pos = int(np.sum(diffs > 1e-9))
    print(f"\n  {n} paired contracts (4 issues x 4 options), same profile both ways")
    print(f"    joint welfare  PEER-vs-PEER:  {pj:.3f}")
    print(f"                   adversarial:   {aj:.3f}   -> peer lift {lift:+.1%}")
    print(f"    worse-off party (fairness)  peer {np.mean(peer_fair):.3f}  vs adv {np.mean(adv_fair):.3f}")
    print(f"    paired sign test: peer >= adversarial in {wins}/{n} ({wins/n:.0%}); "
          f"strictly greater {pos}/{n}")
    print("-" * 74)
    print("  HONEST READ: peer_mode's lift comes from truthful BATNAs (no feasible")
    print("  package wrongly excluded) + cooperative EFFICIENT selection. Both peers")
    print("  choosing the efficient point grows the pie; the worse-off party column")
    print("  shows it isn't achieved by starving one side. It is NOT the lab's")
    print("  +0.186 (LLM self-play, different setup) — it is this engine's own number.")
    return dict(n=n, peer_joint=pj, adv_joint=aj, lift=lift, wins=wins)


if __name__ == "__main__":
    import sys
    if "--peer" in sys.argv:
        run_peer()
    else:
        run()
